# Project information
site_name: IBM University Outreach Programme
site_url: https://davidcolton.github.io/university_outreach_workshop/
site_author: IBM Research
site_description: IBM University Outreach Programme.

# Repository
repo_name: davidcolton/university_outreach_workshop
repo_url: https://github.com/davidcolton/university_outreach_workshop

# Source Docs & Site Docs
docs_dir: "docs"
site_dir: "site"

# navigation
nav:
  - Welcome:
      - About the workshop: index.md
  - Documentation:
      - Lab 0. Pre-work: labs/pre_work.md
      - Lab 1. Getting Started with Mellea: labs/lab_01.md
      - Lab 2. Instruct-Validate-Repair: labs/lab_02.md
      - Lab 3. Compositional Code with Generative Stubs: labs/lab_03.md
      - Lab 4. Document Understanding with Docling: labs/lab_04.md
      - Lab 5. Structured Data with Mellea: labs/lab_05.md
      - Lab 6. Building a Knowledge Base: labs/lab_06.md
      - Lab 7. Putting it all together - Mini Researcher: labs/lab_07.md
  - References:
      - IBM Granite Community: https://github.com/ibm-granite-community
      - Mellea Project: https://mellea.ai/docs/
      - Docling Project: https://github.com/docling-project/docling

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# Theme
theme:
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - content.code.copy
    - navigation.tabs
  name: material
  palette:
    # Palette toggle for light mode

    - scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode

    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2024- IBM Research
