# Project information
site_name: IBM University Outreach Programme
site_url: https://davidcolton.github.io/university_outreach_workshop/
site_author: IBM Research
site_description: IBM University Outreach Programme.

# Repository
repo_name: davidcolton/university_outreach_workshop
repo_url: https://github.com/davidcolton/university_outreach_workshop

# Source Docs & Site Docs
docs_dir: "docs"
site_dir: "site"

# navigation
nav:
  - Welcome:
      - About the workshop: index.md
  - Documentation:
      - Lab 0. Pre-work: pre-work/readme.md
  - Labs:
      - Lab 1. Introduction to LLMs: labs/lab_01.md
      - Lab 2. Getting Started with Mellea: labs/lab_02.md
      - Lab 3. Writing Compositional Code with Generative Stubs: labs/lab_03.md
      - Lab 4. Docling and Mellea: labs/lab_04.md
  - References:
      - IBM Granite Community: https://github.com/ibm-granite-community

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# Theme
theme:
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - content.code.copy
    - navigation.tabs
  name: material
  palette:
    # Palette toggle for light mode

    - scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode

    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2024- IBM Research
